export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "</>", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "✨", color: "#a855f7", isSystem: true },
  { id: "type_command", name: "Command", icon: "$_", color: "#f59e0b", isSystem: true },
  { id: "type_note", name: "Note", icon: "📝", color: "#10b981", isSystem: true },
  { id: "type_file", name: "File", icon: "📄", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "🖼️", color: "#ec4899", isSystem: true },
  { id: "type_url", name: "URL", icon: "🔗", color: "#14b8a6", isSystem: true },
];

export const mockCollections = [
  { id: "col_react", name: "React Patterns", description: "Common React patterns and hooks", isFavorite: true, itemCount: 12 },
  { id: "col_python", name: "Python Snippets", description: "Useful Python code snippets", isFavorite: false, itemCount: 8 },
  { id: "col_context", name: "Context Files", description: "AI context files for projects", isFavorite: true, itemCount: 5 },
  { id: "col_interview", name: "Interview Prep", description: "Technical interview preparation", isFavorite: false, itemCount: 24 },
  { id: "col_git", name: "Git Commands", description: "Frequently used git commands", isFavorite: true, itemCount: 15 },
  { id: "col_ai", name: "AI Prompts", description: "Curated AI prompts for coding", isFavorite: false, itemCount: 18 },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "TEXT" as const,
    content: `import { useSession } from 'next-auth/react'\n\nexport function useAuth() {\n  const { data: session, status } = useSession()\n  return { user: session?.user, isLoading: status === 'loading' }\n}`,
    description: "Custom authentication hook for React applications",
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_react",
    isFavorite: false,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    createdAt: "2026-01-15T10:00:00Z",
    lastUsedAt: "2026-05-15T08:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "TEXT" as const,
    content: `async function fetchWithRetry(url: string, retries = 3): Promise<Response> {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url)\n      if (!res.ok) throw new Error(res.statusText)\n      return res\n    } catch (e) {\n      if (i === retries - 1) throw e\n      await new Promise(r => setTimeout(r, 2 ** i * 1000))\n    }\n  }\n  throw new Error('Max retries reached')\n}`,
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_react",
    isFavorite: false,
    isPinned: true,
    tags: ["typescript", "api", "error-handling"],
    createdAt: "2026-01-12T14:00:00Z",
    lastUsedAt: "2026-05-12T09:00:00Z",
  },
  {
    id: "item_3",
    title: "Git Commit Convention",
    contentType: "TEXT" as const,
    content: "feat: add new feature\nfix: bug fix\nchore: maintenance\ndocs: documentation\nrefactor: code improvement\ntest: add tests",
    description: "Conventional commit message types",
    language: null,
    typeId: "type_command",
    collectionId: "col_git",
    isFavorite: true,
    isPinned: false,
    tags: ["git", "workflow"],
    createdAt: "2026-02-01T09:00:00Z",
    lastUsedAt: "2026-05-10T11:00:00Z",
  },
  {
    id: "item_4",
    title: "Code Review Prompt",
    contentType: "TEXT" as const,
    content: "Review the following code for: security vulnerabilities, performance issues, readability, and adherence to best practices. Provide specific suggestions with examples.",
    description: "General-purpose code review prompt",
    language: null,
    typeId: "type_prompt",
    collectionId: "col_ai",
    isFavorite: true,
    isPinned: false,
    tags: ["code-review", "ai", "prompt"],
    createdAt: "2026-02-10T16:00:00Z",
    lastUsedAt: "2026-05-08T14:00:00Z",
  },
  {
    id: "item_5",
    title: "Python List Comprehension",
    contentType: "TEXT" as const,
    content: "# Filter and transform\nresult = [x * 2 for x in range(10) if x % 2 == 0]\n\n# Nested\nmatrix = [[row[i] for row in matrix] for i in range(len(matrix[0]))]",
    description: "Common list comprehension patterns",
    language: "python",
    typeId: "type_snippet",
    collectionId: "col_python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "list"],
    createdAt: "2026-03-05T10:00:00Z",
    lastUsedAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "item_6",
    title: "CLAUDE.md Template",
    contentType: "TEXT" as const,
    content: "# Project\n\n## Commands\n\n## Architecture\n\n## Conventions\n",
    description: "Starter template for Claude Code context files",
    language: "markdown",
    typeId: "type_note",
    collectionId: "col_context",
    isFavorite: false,
    isPinned: false,
    tags: ["claude", "context", "template"],
    createdAt: "2026-03-20T12:00:00Z",
    lastUsedAt: "2026-04-28T16:00:00Z",
  },
];

export const mockItemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_url: 8,
};
